# -*- coding: utf-8 -*-
"""show_Milhão_Rascunho.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k-E07BJtmvcacSRKSa5YgJ1y-ENo7d45
"""

# Mensagem introdutória e Boas Vindas.
print('****************************************************')
print('*Olá futuro milionário! Por favor, digite seu nome:*')
print('****************************************************')
x = input()
print ('Seja bem-vindo ao Show do Milhão, ' + x )

print ('Vamos ao jogo? Por favor, informe 1 para questões de cultura geral e 2 para questões de Python:')
opcao_pergunta = int(input())

# Criação de uma classe que receberá as informações sobre as questões e respostas

class Questoes:
     def __init__(self, prompt, answer):
          self.prompt = prompt
          self.answer = answer

# Listas recebem as perguntas com as respectivas opções de resposta - Instanciando os objetos

questao_entra_geral = [
     "Qual ano do descobrimento do Brasil?\n(a) 1500\n(b)1620 \n(c)1720 \n",
     "Qual a estrela mais próxima da Terra?\n(a) Ursa Maior\n(b)Alfa Centauro \n(c)Sol \n",
     "Quantos artigos possui a Constituição Americana?\n(a) 12\n(b) 04 \n(c)07 \n",
     "Em qual ano nasceu Alexandre Magno?\n (a) 230 a.C\n (b) 356 d.C\n (c) 356 a.C \n", 
]
questao_entra_python = [
  "Em linhas gerais, o que é uma função ?\n (a) uma lista ordenada de dados\n (b) campo utilizado para inserção de dados\n (c) agrupar um conjunto de instruções para ser reutilizada \n",
  "O nome Python tem origem devido o quê?\n (a) adotaram a Píton como mascote\n (b) seriado de televisão\n (c) homenagem carinhosa à sogra do fundador \n",
  "Qual o benefício de usar tuplas?\n (a) qualquer um pode alterá-la, sem pedir permissão\n (b) pode ordenar dados aleatórios\n (c) melhora no desempenho de busca \n",
  "Na linguagem de programação Python, o método que permite verificar se uma string começa com alguns caracteres é o?\n (a)starswith\n (b) return\n (c) def \n",
]

# Listas com respostas
questao_resposta_geral = [
     Questoes (questao_entra_geral[0], "a"),
     Questoes (questao_entra_geral[1], "b"),
     Questoes (questao_entra_geral[2], "c"),
     Questoes (questao_entra_geral[3], "c"),
]

questao_resposta_python = [
     Questoes(questao_entra_python[0], "c"),
     Questoes(questao_entra_python[1], "b"),
     Questoes(questao_entra_python[2], "c"),
     Questoes(questao_entra_python[3], "a"),
]

def run_quiz(questao_resposta):
     score = 0
     for question in questao_resposta:
          answer = input(question.prompt)
          if answer == question.answer:
               score += 1
     print("Haha... Hihi... você acertou:", score, "Ihhihihi e errou", len(questao_resposta)- score)

if opcao_pergunta == 1: 
  run_quiz(questao_resposta_geral)
elif opcao_pergunta == 2:
  run_quiz(questao_resposta_python)
else:
  print ('Opção Inválida, por favor digite 1 ou 2')